services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: contextbridge
      POSTGRES_USER: contextbridge
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contextbridge"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "80:3001"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://contextbridge:password@postgres:5432/contextbridge
      - JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret}
      - SESSION_SECRET=${SESSION_SECRET:-your-production-session-secret}
      - PORT=3001
      - FRONTEND_URL=https://context-bridge.com
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: